version: '2'

services:
  apollo:
    image: jirry/apollo
    container_name: jirry-apollo
    build:
      context: .
      dockerfile: ${APOLLO_DIR}/apollo/Dockerfile
    depends_on:
      - jirry-apollo-db
    ports:
      - "8060:8080"
      - "8070:8070"
    links:
      - jirry-apollo-db

  jirry-apollo-db:
    image: mysql:5.7
    container_name: jirry-apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - jirry-apollo-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    volumes_from:
      - jirry-apollo-dbdata

  jirry-apollo-dbdata:
    image: alpine:latest
    container_name: jirry-apollo-dbdata
    volumes:
      - /var/lib/mysql