---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/2 18:59
---

-- 声明模块
local hello = {}

-- 模块方法
function hello.world()
    ngx.say("helloWorld!")
end

return hello