---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jirry.
--- DateTime: 2019/7/2 18:04
---
local count = 0

local function hello()
    count = count + 1;
    ngx.say("count:", count);
end

local _M = {
    hello = hello
}

return _M